#注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucq-oauth?setUnicode=true&characterEncoding=utf8
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
   level:
     root: debug

#pagehelper分页插件配置
pagehelper :
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#security
security:
  user:
    password: 123
  basic:
    enabled: false
  oauth2:
    resource:
      id: resource
      user-info-uri: http://localhost:8082/oauth/user
      token-info-uri: http://localhost:8082/oauth/oauth/check_token
      filter-order: 3

    client:
      client-id: lucq-edu
      client-secret: fc0df819e82858352626c113d963d75a
      grant-type: password
      scope: read
      access-token-uri: http://localhost:8082/oauth/oauth/token
      user-authorization-uri: http://localhost:8082/oauth/oauth/authorize
    authorization:
      check-token-access: http://localhost:8082/oauth/oauth/check_token


